#!/bin/bash

NAME="scheduler"                                  # Name of the application
DJANGODIR=/opt/scheduler/scheduler
SOCKFILE=/opt/scheduler/run/gunicorn.sock
USER=scheduler
GROUP=webapps
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=scheduler.settings
DJANGO_WSGI_MODULE=scheduler.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /opt/scheduler/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /opt/scheduler/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
